#!/usr/bin/env bash
# Set the Internal Field Separator to colon
IFS=":"

# Read the /etc/passwd file line by line
while read -r username password userid groupid info homedir shell; do
    echo "The user $username (User ID: $userid) is part of the $groupid gang, lives in $homedir and rides $shell. USER ID's place is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd

