#!/usr/bin/env bash
# Read the /etc/passwd file line by line
while IFS=: read -r username password user_id group_id user_info home_directory shell; do
    # Format and display the story for each user
    echo "The user $username is part of the $group_id gang, lives in $home_directory and rides $shell. $user_id's place is protected by the passcode $password, more info about the user here: $user_info"
done < /etc/passwd
