#!/usr/bin/env bash
# Specify the path to your Apache access log file
log_file="apache-access.log"

awk '{print $1, $9}' "$log_file" | \
    awk '{count[$1, $2]++} END {for (key in count) print count[key], key}' | \
    sort -nr

