#!/usr/bin/env bash
# Initialize the loop counter
i=1
while [ $i -le 10 ]
do
  if [ $i -eq 9 ]
  then
    echo "Best School"
    echo "Hi"
  else
    echo "Best School"
  fi
  ((i++))  # Increment the counter by 1
done
