#!/usr/bin/env bash
# initialize counter
i=1
while [ $i -le 20 ]
do	
  case $i in
   4)
      echo "$i -bad luck from china"
      ;;
   9)
      echo  "$i -bad luck from japan"
      ;;
  17)
      echo "$i -bad luck from italy"
      ;;
   *)
      echo "$i"
esac
i=$((i+ 1))
done
