#!/usr/bin/env bash
i=1
while [ $i -le 10]
do 
    if [ $i eq 4 ] 
    then
       echo "bad luck"
    else 
        echo "Best school"
    if [ $i eq 8 ] 
      then 
        echo "good luck"
      else
        echo "good luck"
      fi
      ((i++)) 
   done
